openapi: '3.0.2'
info:
  title: Masp Indexer
  version: '1.0'
servers:
  - url: https://localhost:5000/api/v1
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
  /commitment-tree:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The commitment tree at the given height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TreeResponse'
  /height:
    get:
      responses:
        '200':
          description: The last indexed block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestHeightResponse'
  /notes-map:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The notes map up to some block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotesMapResponse'
  /witness-map:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The witness map of a specific block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WitnessMapResponse'
  /tx:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
        - in: query
          name: height_offset
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The masp transactions between `height` and `height + height_offset`.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxResponse'

components:
  schemas:
    TreeResponse:
      type: object
      properties:
        commitment_tree:
          type: string
          format: byte
          description: The commitment tree bytes.
        block_height:
          type: integer
          minimum: 0
          description: The block height of the commitment tree.
    LatestHeightResponse:
      type: object
      properties:
        block_height:
          type: integer
          minimum: 0
          description: The last indexed block height.
    WitnessMapResponse:
      type: object
      properties:
        witnesses:
          type: array
          items:
            type: object
            properties:
              bytes:
                type: string
                format: byte
                description: The witness bytes.
              index:
                type: integer
                minimum: 0
                description: The witness index.
          description: The commitment tree bytes.
        block_height:
          type: integer
          minimum: 0
          description: The block height of the commitment tree.
    NotesMapResponse:
      type: object
      properties:
        notes_map:
          type: array
          items:
            type: object
            properties:
              note_position:
                type: integer
                minimum: 0
                description: The note position.
              index:
                type: integer
                minimum: 0
                description: The note index.
              is_fee_unshielding:
                type: boolean
                description: If this is s fee unshielded.
              block_height:
                type: integer
                minimum: 0
                description: The note block height.
          description: The vector of notes map.
    TxResponse:
      type: object
      properties:
        txs:
          type: array
          items:
            type: object
            properties:
              bytes:
                type: string
                format: byte
                description: The masp transaction bytes.
              index:
                type: integer
                minimum: 0
                description: The note index.
              block_height:
                type: integer
                minimum: 0
                description: The note block height.
          description: The vector of masp transactions.
